DROP TABLE IF EXISTS public.students;

CREATE TABLE public.students
(
    "id" SERIAL PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(100) NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "email_lower" VARCHAR(100) GENERATED ALWAYS AS (lower("email")) STORED,
    UNIQUE ("email_lower")
);

DROP TABLE IF EXISTS public.tests;

CREATE TABLE public.tests
(
    "id" SERIAL PRIMARY KEY,
    "title" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS public.questions;

CREATE TABLE public.questions
(
    "id" SERIAL PRIMARY KEY,
    "test_id" INTEGER NOT NULL REFERENCES public.tests("id") ON DELETE CASCADE,
    "question" VARCHAR(255) NOT NULL,
    "answer" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS public.enrollments;

CREATE TABLE public.enrollments
(
    "id" SERIAL PRIMARY KEY,
    "student_id" INTEGER NOT NULL REFERENCES public.students("id") ON DELETE CASCADE,
    "test_id" INTEGER NOT NULL REFERENCES public.tests("id") ON DELETE CASCADE,
    "enrolled_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE ("student_id", "test_id")
);
