// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: pb/test.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TestService_GetTest_FullMethodName            = "/test.TestService/GetTest"
	TestService_CreateTest_FullMethodName         = "/test.TestService/CreateTest"
	TestService_CreateQuestions_FullMethodName    = "/test.TestService/CreateQuestions"
	TestService_EnrollStudents_FullMethodName     = "/test.TestService/EnrollStudents"
	TestService_GetStudentsPerTest_FullMethodName = "/test.TestService/GetStudentsPerTest"
)

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestServiceClient interface {
	GetTest(ctx context.Context, in *GetTestRequest, opts ...grpc.CallOption) (*Test, error)
	CreateTest(ctx context.Context, in *Test, opts ...grpc.CallOption) (*TestResponse, error)
	CreateQuestions(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Question, SimpleStreamResponse], error)
	EnrollStudents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EnrollmentRequest, SimpleStreamResponse], error)
	GetStudentsPerTest(ctx context.Context, in *GetStudentsPerTestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Student], error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) GetTest(ctx context.Context, in *GetTestRequest, opts ...grpc.CallOption) (*Test, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Test)
	err := c.cc.Invoke(ctx, TestService_GetTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) CreateTest(ctx context.Context, in *Test, opts ...grpc.CallOption) (*TestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, TestService_CreateTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) CreateQuestions(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Question, SimpleStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[0], TestService_CreateQuestions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Question, SimpleStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_CreateQuestionsClient = grpc.ClientStreamingClient[Question, SimpleStreamResponse]

func (c *testServiceClient) EnrollStudents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EnrollmentRequest, SimpleStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[1], TestService_EnrollStudents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EnrollmentRequest, SimpleStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_EnrollStudentsClient = grpc.ClientStreamingClient[EnrollmentRequest, SimpleStreamResponse]

func (c *testServiceClient) GetStudentsPerTest(ctx context.Context, in *GetStudentsPerTestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Student], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[2], TestService_GetStudentsPerTest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetStudentsPerTestRequest, Student]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_GetStudentsPerTestClient = grpc.ServerStreamingClient[Student]

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility.
type TestServiceServer interface {
	GetTest(context.Context, *GetTestRequest) (*Test, error)
	CreateTest(context.Context, *Test) (*TestResponse, error)
	CreateQuestions(grpc.ClientStreamingServer[Question, SimpleStreamResponse]) error
	EnrollStudents(grpc.ClientStreamingServer[EnrollmentRequest, SimpleStreamResponse]) error
	GetStudentsPerTest(*GetStudentsPerTestRequest, grpc.ServerStreamingServer[Student]) error
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestServiceServer struct{}

func (UnimplementedTestServiceServer) GetTest(context.Context, *GetTestRequest) (*Test, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTest not implemented")
}
func (UnimplementedTestServiceServer) CreateTest(context.Context, *Test) (*TestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTest not implemented")
}
func (UnimplementedTestServiceServer) CreateQuestions(grpc.ClientStreamingServer[Question, SimpleStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method CreateQuestions not implemented")
}
func (UnimplementedTestServiceServer) EnrollStudents(grpc.ClientStreamingServer[EnrollmentRequest, SimpleStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method EnrollStudents not implemented")
}
func (UnimplementedTestServiceServer) GetStudentsPerTest(*GetStudentsPerTestRequest, grpc.ServerStreamingServer[Student]) error {
	return status.Error(codes.Unimplemented, "method GetStudentsPerTest not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}
func (UnimplementedTestServiceServer) testEmbeddedByValue()                     {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	// If the following call panics, it indicates UnimplementedTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_GetTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).GetTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_GetTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).GetTest(ctx, req.(*GetTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_CreateTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Test)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).CreateTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_CreateTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).CreateTest(ctx, req.(*Test))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_CreateQuestions_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).CreateQuestions(&grpc.GenericServerStream[Question, SimpleStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_CreateQuestionsServer = grpc.ClientStreamingServer[Question, SimpleStreamResponse]

func _TestService_EnrollStudents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).EnrollStudents(&grpc.GenericServerStream[EnrollmentRequest, SimpleStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_EnrollStudentsServer = grpc.ClientStreamingServer[EnrollmentRequest, SimpleStreamResponse]

func _TestService_GetStudentsPerTest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetStudentsPerTestRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestServiceServer).GetStudentsPerTest(m, &grpc.GenericServerStream[GetStudentsPerTestRequest, Student]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_GetStudentsPerTestServer = grpc.ServerStreamingServer[Student]

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTest",
			Handler:    _TestService_GetTest_Handler,
		},
		{
			MethodName: "CreateTest",
			Handler:    _TestService_CreateTest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateQuestions",
			Handler:       _TestService_CreateQuestions_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "EnrollStudents",
			Handler:       _TestService_EnrollStudents_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetStudentsPerTest",
			Handler:       _TestService_GetStudentsPerTest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/test.proto",
}
